name: Trigger
on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: windows-latest

    permissions:
      contents: write

    env:
      ASSET_RIPPER_VERSION: "0.3.4.0"

    steps:
    # ==========================
    # 1. Checkout repo
    # ==========================
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.bla }}
        fetch-depth: 0

    # ==========================
    # 1.5 Restore asset_metadata.json
    # (ensures try.py can read previous metadata)
    # ==========================
    - name: Restore asset metadata
      run: |
        if (Test-Path "asset_metadata.json") {
        Write-Output "asset_metadata.json found."
        } else {
        "{}" | Out-File asset_metadata.json -Encoding utf8
        Write-Output "Created empty asset_metadata.json"
        }

    # ==========================
    # 2. Download main bin file
    # ==========================
    - name: Download CloudFront file
      run: |
        curl.exe -L "${{secrets.link1}}" -o target.bin

    # ==========================
    # 3. Python setup
    # ==========================
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install UnityPy & requests
      run: |
        python -m pip install --upgrade pip
        pip install UnityPy
        pip install requests
                
    # ==========================
    # 4. Run Python script
    # ==========================
    - name: Run try.py
      run: |
        python "try.py" "target.bin"

    # ==========================
    # 5. Commit & push results
    # ==========================
    - name: Push output to GitHub
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit -m "Auto-update output from workflow" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.bla }}
