name: Trigger
on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: windows-latest

    permissions:
      contents: write   # Required for git push using GITHUB_TOKEN

    env:
      ASSET_RIPPER_VERSION: "0.3.4.0"

    steps:
    # ==========================
    # 1. Checkout repo
    # ==========================
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.bla }}   # Must allow writes
        fetch-depth: 0


    # ==========================
    # 3. Python setup
    # ==========================
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install requests
      run: |
        python -m pip install --upgrade pip

        pip install requests
                
    # ==========================
    # 4. Run Python script
    # ==========================
    - name: Run try.py
      run: |
        python "try.py" "target.bin"
    # ==========================
    # 5. Commit & push results
    # ==========================
    - name: Push output to GitHub
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Auto-update output from workflow" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.bla }}   # or ${{ secrets.GITHUB_TOKEN }}
